name: Manage Merge
description: "Manage merge pull requests on date for target branch"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "git-merge"
  color: green
inputs:
  merge_method:
    description: |-
      Merge method to use. Possible values are `merge`, `squash` or
      `rebase`. Default is `merge`.
    required: false
    default: merge
  time_zone:
    description: |-
     Time zone to use. Default is UTC.
    required: false
    default: UTC
  target_branch:
    description: |-
     Target branch, pull requested created for.
    required: false
    default: main
  label_name:
    description: |-
     Target branch's label to make sure branch that branch is ready for merge, if any label is given.
    required: false
    default: merge-ready
